version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    expose:
      - 9200
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  keycloak:
    image: jboss/keycloak:4.5.0.Final
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    expose:
      - 8080
      - 8787
    command:
      - "--debug"
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/example-realm.json"
    ports:
      - "8080:8080"
    volumes:
      - ./example-realm.json:/opt/jboss/keycloak/example-realm.json