
image:
  repository: novomatic/elasticsearch-proxy
  pullPolicy: IfNotPresent
  # pullSecrets: pull-secrets

commandline:
  args:
  ## Example:
  # - server.port 19200

env: {}
## Example:
# server.port: 19200

# Content of the application.yaml file
configuration:
  server:
    port: 19200

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  timeoutSeconds: 10
  # failureThreshold:
  # successThreshold:

readinessProbe:
  enabled: true
  initialDelaySeconds: 60
  timeoutSeconds: 10
  # failureThreshold:
  # successThreshold:

service:
  type: ClusterIP
  externalPort: 19200
  annotations:
  # Annotation example: setup ssl with aws cert when service.type is LoadBalancer
  # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:EXAMPLE_CERT
  labels:
  ## Label example: show service URL in `kubectl cluster-info`
  # kubernetes.io/cluster-service: "true"

priorityClassName: ""

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi

# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
# affinity: {}

# Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

podAnnotations: {}
replicaCount: 1
revisionHistoryLimit: 3