apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elasticsearch-proxy.fullname" . }}
  labels:
    app: {{ template "elasticsearch-proxy.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |
{{ toYaml .Values.configuration | default "{}" | indent 4 }}